import 'package:flutter/material.dart';

class ConfigureScreen extends StatefulWidget {
  ConfigureScreen({super.key});
  bool sprinklerState = false;
  @override
  State<ConfigureScreen> createState() => _ConfigureScreenState();
}

class _ConfigureScreenState extends State<ConfigureScreen> {
  double distanceTraveled = 5.24;
  double SPIAR_width = 3;

  @override
  Widget build(BuildContext context) {
    List<ListTileStrings> infoTiles = [
      ListTileStrings(
          'Distance traveled', '', '${distanceTraveled.toString()} km'),
      ListTileStrings('Area covered', '',
          '${(distanceTraveled * SPIAR_width / 10).toString()} ha'),
      ListTileStrings('Power generated by solar panels', '', '122.3 KW'),
      ListTileStrings('Battery remaining (%)', '', '56%'),
      ListTileStrings(
          'Battery autonomy remaining', '(hours, w/o solar panels)', '10.2h'),
      ListTileStrings(
          'Battery autonomy remaining', '(hours, with solar panels)', '16.4h'),
      ListTileStrings('Battery health', '', '100%'),
    ];

    return Scaffold(
      appBar: AppBar(title: const Text('Admin Panel')),
      body: ListView(
        children: [
          const ListTile(
            title: Text(
              'INFO',
              style: TextStyle(fontSize: 30, fontWeight: FontWeight.bold),
            ),
          ),
          ...infoTiles.map((e) => ListTile(
              title: Text(e.title),
              subtitle: e.subtitle != '' ? Text(e.subtitle) : null,
              trailing: Text(e.trailing))),
          const ListTile(
            title: Text(
              'SETTINGS',
              style: TextStyle(fontSize: 30, fontWeight: FontWeight.bold),
            ),
          ),
          SwitchListTile(
            title: const Text('Sprinklers'),
            value: widget.sprinklerState,
            onChanged: (e) {
              setState(() {
                widget.sprinklerState = e;
              });
            },
            secondary: const ImageIcon(AssetImage('images/sprinkler_icon.png')),
          ),
          // Center(
          //   child: Wrap(
          //     children: [
          //       ElevatedButton(
          //         onPressed: () {},
          //         child: const Text('Force Stop'),
          //       ),
          //     ],
          //   ),
          // ),
        ],
      ),
    );
  }
}

class ListTileStrings {
  late String title, subtitle, trailing;
  ListTileStrings(this.title, this.subtitle, this.trailing);
}
